# Generated by Django 5.2.5 on 2025-12-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VISA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_name', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('C_number', models.IntegerField()),
                ('C_W_number', models.CharField(max_length=110)),
                ('C_email', models.EmailField(max_length=254)),
                ('C_description', models.TextField(max_length=2000)),
            ],
        ),
    ]
